build:
    nodes:
        tests:
            environment:
                java: 'java-8-oracle'
                timezone: FR

            tests:
                override:
                    - command: mvn test
                      coverage:
                        file: 'target/jacoco.exec'
                        format: 'jacoco'
