build:
    nodes:
      analysis:
        dependencies:
          override:
            - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -B -V

        tests:
            environment:
                java: 'java-8-oracle'
                timezone: FR

            dependencies:
              override:
                - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -B -V

            tests:
                override:
                    - command: mvn test -pl arakne-encoding
                      coverage:
                        file: 'arakne-encoding/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: mvn checkstyle:checkstyle -pl arakne-encoding
                      analysis:
                        file: 'arakne-encoding/target/checkstyle-result.xml'
                        format: 'general-checkstyle'
                    - command: mvn test -pl arakne-value
                      coverage:
                        file: 'arakne-value/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: mvn checkstyle:checkstyle -pl arakne-value
                      analysis:
                        file: 'arakne-value/target/checkstyle-result.xml'
                        format: 'general-checkstyle'
                    - command: mvn test -pl arakne-map
                      coverage:
                        file: 'arakne-map/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: mvn checkstyle:checkstyle -pl arakne-map
                      analysis:
                        file: 'arakne-map/target/checkstyle-result.xml'
                        format: 'general-checkstyle'
                    - command: mvn pitest:mutationCoverage
