build:
    nodes:
        tests:
            environment:
                java: 'java-8-oracle'
                timezone: FR

            tests:
                override:
                    - command: mvn test -pl arakne-encoding
                      coverage:
                        file: 'arakne-encoding/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: mvn test -pl arakne-value
                      coverage:
                        file: 'arakne-value/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: mvn test -pl arakne-map
                      coverage:
                        file: 'arakne-map/target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: 'mvn checkstyle:checkstyle'
                      analysis:
                        file: 'target/checkstyle-result.xml'
                        format: 'general-checkstyle'
